#!/bin/sh
exec 2>&1
deps="%HOME%/service/dependencies"
if [ -s "$deps" ]; then
    svlist=$(cat "$deps")
    sv start $svlist || exit 1
fi
export HOME="%HOME%"
export USER="%USER%"
groups="$(id -Gn "%USER%" | tr ' ' ':')"
exec chpst -u "%USER%:$groups" runsvdir "%HOME%/service/sv"
